name: Build executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
        with:
          repository: 'k1tbyte/Wand-Enhancer'
          ref: '1.0.5.0'

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v3
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Proxy DLL (CMake)
        shell: pwsh
        run: |
          cd tools/asar-fuses-bypass
          cmake -B cmake-build-release
          cmake --build cmake-build-release --config Release
          # Windows CMake puts the output in a Release subfolder, so we move it to where MSBuild is looking
          if (Test-Path "cmake-build-release\Release\version.dll") {
              Copy-Item "cmake-build-release\Release\version.dll" -Destination "cmake-build-release\version.dll"
          }

      - name: Restore NuGet packages
        run: nuget restore Wemod-Patcher.sln

      - name: Build legacy executable
        run: msbuild Wemod-Patcher.sln -p:Configuration=Release -p:Platform="Any CPU"

      - name: Upload legacy executable
        uses: actions/upload-artifact@v4
        with:
          name: WandEnhancer-1.0.5.0
          path: "**/bin/Release/**/*.exe"
          if-no-files-found: error
