name: Build executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
        with:
          ref: '1.0.5.0'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build legacy executable
        run: msbuild -p:Configuration=Release

      - name: Upload legacy executable
        uses: actions/upload-artifact@v4
        with:
          name: WandEnhancer-1.0.5.0
          path: "**/bin/Release/*.exe"
          if-no-files-found: error
